### ISSUE TITLE
Allow configuration of the HTTP connection timeout

### ISSUE THREAD

**Issue by atakiya** [Gawdl3y/Resolute#120]
As title, environments with unstable connections are entirely unable to download mods with Resolute.
Due to a temporary situation, my average latency times are quite high, and Resolute seems to not like that, as I get timeout errors as the image below.

![image](https://github.com/Gawdl3y/Resolute/assets/6952402/25fca9d1-3431-43b4-8608-e71afaffdc29)

it is to note that regular downloads of the files via browsers, download managers and such are possible.

<details>
<summary>Latency test to nearest CF edge of my connection for reference</summary>

![image](https://github.com/Gawdl3y/Resolute/assets/6952402/a625c676-6b15-443c-be9e-2e7c29bfd800)

</details>

I'm aware that this is most likely not a priority, but a more robust download system would definitely be of benefit. Or at least a way to set a manual timeout value that is not as strict.

**Comment by Gawdl3y** [comment]
Interesting. Those latency charts don't show anything too crazy (roughly 200ms max), and certainly nothing past the hard-coded timeout (10 seconds). Do you encounter web pages taking a really long time to load even the first part of the page (longer than 10 seconds) in normal web browser use as well?

**Comment by atakiya** [comment]
> Interesting. Those latency charts don't show anything too crazy (roughly 200ms max?), and certainly nothing past the hard-coded timeout (10 seconds). Do you encounter web pages taking a really long time to load even the first part of the page (longer than 10 seconds) in normal web browser use as well?

They do show spikes >1200ms, those aren't too common but enough that it disrupts some applications that are more strict.
Tested if it hits the timeout limit and indeed it is hitting it, erroring after 10s.

> Do you encounter web pages taking a really long time to load even the first part of the page (longer than 10 seconds) in normal web browser use as well?

Not longer than the average latency times or spikes, so at max it would be around 3000ms before I would get a connection established, after which things load relatively quick and at the full speed of my WAN connection. See the example below.

### Example of a download from `objects.githubusercontent.com`

https://github.com/Gawdl3y/Resolute/assets/6952402/87698b2f-fd29-4a73-87e0-8062e4d437b6

Seems that it takes around 11 seconds for the connection to be established on the above.
I assume this is because of redirects from the userfacing download url, and each new connection applies an additional delay, which then counts up beyond the 10s timeout.

**Comment by Gawdl3y** [comment]
I'm hoping to get a release out today or tomorrow, and this new setting will be in it.

**Comment by Gawdl3y** [comment]
This is now in version 0.7.0!
