### ISSUE TITLE
Unable to install Resolute on Windows with WebView2 and Edge removed

### ISSUE THREAD

**Issue by Ianthasys** [Gawdl3y/Resolute#47]
The installation .exe fails installing webview2 when I run it. My assumption is that this is because I've removed Edge via       https://github.com/AveYo/fox

I'm assuming WebView is a dependency for the app? If so, it may be a good idea to add that info to the readme, as It's not too uncommon for folk to remove webview and edge together.

![image](https://github.com/Gawdl3y/Resolute/assets/100318148/68c316fd-4711-41de-9121-acf95a1fb18d)

**Comment by Gawdl3y** [comment]
Yes, Tauri (the app framework Resolute is built upon) uses your operating system's WebView for rendering. On Windows, that's WebView2. If you've removed that from the OS without any kind of replacement (I don't think it's even possible to seamlessly replace WebView2 with anything else atm), it's not going to be able to work. WebViews are a core component of operating systems and it's typically not a great idea to remove them. The only alternative to this is shipping an embedded version of a browser with the software, like what Electron does with Chrome, and we all know how people *love* Electron apps. ;)

The readme does mention that it uses the system WebView, though that could perhaps be mentioned in a more obvious spot.

**Comment by Gawdl3y** [comment]
Added a prominent notice to the readme in #51.
