### ISSUE TITLE
Use steamlocate crate instead of looking for Steam manually

### ISSUE THREAD

**Issue by art0007i** [Gawdl3y/Resolute#59]
there is a crate called steamloacte (https://crates.io/crates/steamlocate/) which can easily find steam library folders, and even a specific app like resonite, though this library has some known bugs in it's current latest release and I'd probably wait until they release 2.0.0 (which they probably will soon, considering there is already a beta version)

**Comment by Gawdl3y** [comment]
Thanks for the suggestion! I implemented the use of steamlocate in the [feat/resonite-discovery-steamlocate branch](https://github.com/Gawdl3y/Resolute/tree/feat/resonite-discovery-steamlocate), but found a bug with the library that causes it to fail when an ACF contains lowercase fields. I reported that to them (WilliamVenner/steamlocate-rs#58), so will probably merge the branch into main once they resolve it.
