### ISSUE TITLE
Default pagination behaviour is unintuitive with the grouped mod list

### ISSUE THREAD

**Issue by xboxnoob** [Gawdl3y/Resolute#76]
As title mentions the all mods list scroll bar doesn't reach the bottom when more than a couple categories are expanded

**Comment by Gawdl3y** [comment]
The mod list is paginated. Once you expand several categories, you're probably getting enough items in the list to push items to the next page. 

![image](https://github.com/Gawdl3y/Resolute/assets/279900/a8235016-6abb-4205-bb62-4d7fe8d61e2b)

Note that the "Items per page" dropdown currently has to be re-selected every time the All Mods tab is visited if you want something other than the default 25 - I'm probably going to make this choice persist in the future.

**Comment by xboxnoob** [comment]
the pagination is a bit awkward and obtuse when you have collapsible categories
